environment:
  release_version: '1.7.0-beta2'
  assembly_version: '1.7.0'

version: '$(release_version)+{build}'
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: Source\**\AssemblyInfo.*
  assembly_version: '$(assembly_version).{build}'
  assembly_file_version: '$(assembly_version).{build}'
  assembly_informational_version: '$(release_version)'
before_build:
- cmd: >-
    powershell -f patch-vsix-version.ps1 -version "%ASSEMBLY_VERSION%.%APPVEYOR_BUILD_NUMBER%" -manifestFile "Source\Machine.VSTestAdapter.VSIX\source.extension.vsixmanifest"

    nuget restore
build:
  project: machine.vstestadapter.sln
  publish_nuget: true
  verbosity: minimal
test:
  assemblies: '**\*.Specs.dll'
artifacts:
- path: '**\*.vsix'
- path: Source\**\*.nupkg