environment:
  nuget_version: '2.0.0-beta3'
  vsix_version: '2.0.0'
  assembly_version: '2.0.0'

version: '$(nuget_version)+{build}'
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: Source\**\AssemblyInfo.*
  assembly_version: '$(assembly_version).{build}'
  assembly_file_version: '$(assembly_version).{build}'
  assembly_informational_version: '$(nuget_version)'
before_build:
- cmd: >-
    powershell -f patch-vsix-version.ps1 -version "%VSIX_VERSION%.%APPVEYOR_BUILD_NUMBER%" -manifestFile "Source\Machine.VSTestAdapter.VSIX\source.extension.vsixmanifest"

    nuget restore
build:
  project: machine.vstestadapter.sln
  publish_nuget: true
  verbosity: minimal
test:
  assemblies: '**\*.Specs.dll'
artifacts:
- path: '**\*.vsix'
- path: Source\**\*.nupkg